### ISSUE TITLE
Platforms: Mario Kart 8 / Deluxe

### ISSUE THREAD

**Issue by Maelstromeous** [Maelstromeous/mariokart.fun#9]
Mario Kart 8 has the following differences, in exception to new characters, vehicles, tracks etc.

# Todo

- [x] Enter new characters into database
- [ ] Enter new vehicles into database
- [ ] Enter new tracks into database
- [ ] Enter new vehicle parts into database
    - [ ] Figure out how the parts affect gameplay.
    - [ ] Consider whether to actually show these differences and whether they're relevant in any significant way (how the hell do we show stats for different vehicles and parts?)
- [ ] Acquire character images
- [ ] Acquire vehicle images
- [ ] Acquire track images
- [ ] Acquire vehicle part images

# Weight classes

* The character's weights are now split into Light, Light2, Medium, Medium2, Heavy, Heavy2.

http://www.nintendolife.com/news/2014/07/guide_all_you_need_to_know_on_mario_kart_8_characters_and_kart_customisations

![Image](http://images.nintendolife.com/news/2014/07/guide_all_you_need_to_know_on_mario_kart_8_characters_and_kart_customisations/attachment/2/original.jpg)

# Vehicles

There's new kinds of vehicles in MK8. They go off a frame system rather than vehicles themselves, to which you add parts to change attributes of the base vehicle.

http://mariokart.wikia.com/wiki/Mario_Kart_8#Vehicle_parts

In order to accomodate for this, if I'm to show the stat bars at all for MK8 due to it's complexity, I'd have to factor in the vehicle parts and adjust the appropiate stat bars accordingly. Shouldn't be too difficult if I can create a matrix of what part affects what attribute, then adjust the bar accordingly.

# Attributes

In MK8 the attributes have changed. They've been split into subcategories:

* Speed
    * Ground
    * Water
    * Air
    * Anti-Gravity
* Acceleration
* Weight
* Handling
    * Ground
    * Water
    * Air
    * Anti-Gravity
* Traction
* Mini-turbo

** Drift has been removed **.

NOTE: Attributes are goverened by the character, NOT the vehicle. Further modifiers are applied by both the vehicle, **and** it's parts.

This will likely mean I have to scrap the vehicles attributes table, or rename it to platform specific ones.
